# Generated by Django 2.1.2 on 2019-07-02 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umap', '0006_auto_20190702_0712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wmscategory',
            options={'ordering': ('name', 'abreviation'), 'verbose_name': 'WMS category', 'verbose_name_plural': 'WMS categories'},
        ),
        migrations.RenameField(
            model_name='tilelayerwms',
            old_name='wmscategory',
            new_name='wms_category',
        ),
    ]
