# Generated by Django 2.1.2 on 2019-07-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umap', '0010_auto_20190702_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wmscategory',
            name='wmsprovider',
        ),
        migrations.AddField(
            model_name='wmscategory',
            name='provider',
            field=models.CharField(default='Other', help_text='Data provider', max_length=255),
        ),
    ]
