# Generated by Django 2.1.2 on 2019-07-02 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umap', '0012_auto_20190702_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='WMSProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Other', help_text='Provider full name', max_length=200, unique=True)),
                ('abreviation', models.CharField(default='OT', help_text='Short name', max_length=5, unique=True)),
                ('rank', models.SmallIntegerField(blank=True, help_text='Order of the providers in the edit box', null=True)),
            ],
            options={
                'verbose_name': 'WMS provider',
                'verbose_name_plural': 'WMS providers',
                'ordering': ('name', 'abreviation'),
            },
        ),
        migrations.RemoveField(
            model_name='wmscategory',
            name='provider',
        ),
        migrations.AlterField(
            model_name='wmscategory',
            name='name',
            field=models.CharField(default='Other', help_text='Category full name', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='wmscategory',
            name='wmsprovider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='umap.WMSProvider'),
        ),
    ]
