# Generated by Django 2.1.2 on 2019-07-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umap', '0014_remove_wmscategory_wmsprovider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WMSProvider',
        ),
        migrations.AddField(
            model_name='wmscategory',
            name='provider',
            field=models.CharField(default='Other', help_text='Data provider', max_length=255),
        ),
        migrations.AlterField(
            model_name='wmscategory',
            name='name',
            field=models.CharField(default='Other', help_text='Category name', max_length=200, unique=True),
        ),
    ]
