# Generated by Django 2.1.2 on 2019-07-02 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umap', '0016_auto_20190702_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='tilelayerwms',
            name='wms_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='umap.WMSProvider'),
        ),
    ]
