# Generated by Django 2.1.2 on 2019-07-02 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umap', '0018_remove_tilelayerwms_wms_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmscategory',
            name='wmsprovider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='umap.WMSProvider'),
        ),
    ]
