# Generated by Django 2.1.2 on 2019-07-02 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umap', '0020_auto_20190702_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wmscategory',
            options={'ordering': ('name', 'abreviation'), 'verbose_name': 'WMS category', 'verbose_name_plural': 'WMS categories'},
        ),
    ]
