# Generated by Django 2.1.2 on 2019-07-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umap', '0026_auto_20190702_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='wmscategory',
            name='wms_provider',
            field=models.CharField(blank=True, default='unknown', max_length=300),
        ),
        migrations.AlterField(
            model_name='tilelayerwms',
            name='attribution',
            field=models.CharField(blank=True, default='unknown', max_length=300),
        ),
        migrations.AlterField(
            model_name='tilelayerwms',
            name='wms_category',
            field=models.CharField(blank=True, default='unknown', max_length=300),
        ),
        migrations.AlterField(
            model_name='tilelayerwms',
            name='wms_provider',
            field=models.CharField(blank=True, default='unknown', max_length=300),
        ),
    ]
