# Generated by Django 2.1.2 on 2020-02-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umap', '0033_auto_20200217_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='latviacs',
            name='sustCheck',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='latviacs',
            name='method',
            field=models.SmallIntegerField(choices=[(0, 'Areas where all of the criteria apply'), (1, 'Areas where at least one of the criteria apply')], default=0),
        ),
    ]
