# Generated by Django 2.1.2 on 2020-06-02 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('umap', '0036_auto_20200403_1256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LatviaCS',
        ),
    ]
